# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Película')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/', verbose_name='Imagen')),
                ('duracion', models.CharField(max_length=25, verbose_name='Duración')),
                ('director', models.CharField(max_length=50, verbose_name='Director')),
                ('actores', models.TextField(verbose_name='Actores')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('trailer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trailer')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Genero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pais')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
